# Generated by Django 4.1.5 on 2025-06-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un', models.CharField(max_length=20)),
                ('em', models.CharField(max_length=40)),
                ('mss', models.CharField(max_length=60)),
            ],
        ),
    ]
